### ISSUE TITLE
Mobile social login

### ISSUE THREAD

**Issue by kronik** [baasbox/DearDiary-iOS#1]
Hi,

Is there any example how to implement mobile social login? I tried to add /socia/:type api call into the BAAClient but can't figure out what to pass as a oauth_secret for the Facebook social login type. I tried to pass app secret key but always get an error response:
message = "Both oauth_token and oauth_secret should be specified in the query string";

Could you please clarify how to do this properly?

**Comment by FairApril** [comment]
I am getting this error:
 UserInfo=0x7fec28527850 {iOS SDK Version=0.9.0, NSLocalizedDescription=Unable to validate provided token, BaasBox_API_version=(
    "0.9.4"
)}

I don't know how it won't accept the token. I verified the token through an http call and it was valid. Why BaasBox is not accepting it?

I am using this function:
- (void) loginWithGoogleToken:(NSString *)token completion:(BAABooleanResultBlock)completionBlock
